### ISSUE TITLE
Published artifacts with incorrect liquibase core version

### ISSUE THREAD

**Issue by mcred** [liquibase/liquibase-redshift#146]
The pom for the published artifacts differ from the pom in the repo:

https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-redshift/4.21.1/liquibase-redshift-4.21.1.pom

liquibase.version should be 4.21.1 instead of 4.19.0.

**Comment by filipelautert** [comment]
Hello @mcred ! It has been finally fixed here -> https://repo1.maven.org/maven2/org/liquibase/ext/liquibase-redshift/4.23.0.1/
