### ISSUE TITLE
Invalid operation: syntax error at or near "TAG"

### ISSUE THREAD

**Issue by radoslawjakubowski** [liquibase/liquibase-redshift#6]
Not sure if anybody is monitoring this project, but for reference I got this error today:
`liquibase.exception.DatabaseException: [Amazon](500310) Invalid operation: syntax error at or near "TAG"
Position: 307; [Failed SQL: CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]`

It seems this needs to be resolved in liquibase core.

**Comment by radoslawjakubowski** [comment]
I wasn't using explicitly RedshiftDatabase class, for some reason liquibase returs PostgresDatabase object when using findCorrectDatabaseImplementation method.

When forcing RedshiftDatabase I got different error:
`[Amazon][JDBC](11340) Not all output parameters are registered.`

**Comment by radoslawjakubowski** [comment]
My mistake. When explicitly setting RedshiftDatabase in liquibase it works as expected.

**Comment by dshriyan** [comment]
How was this resolved?

**Comment by akamathEG** [comment]
Yeah, what did you mean by explicitly setting RedshiftDatabase in liquibase? @radoslawjakubowski

**Comment by r2liquibase** [comment]
Our friends at AWS Redshfit helped write these updated instructions. Do they help @akamathEG ?

https://docs.liquibase.com/workflows/database-setup-tutorials/redshift.html

**Comment by akamathEG** [comment]
Thanks for getting back @r2liquibase , I've seen this tutorial and am trying to run liquibase update programmatically via Java, but I'm wondering how could I use a SQL file instead - do I simply replace the xml file path below with the SQL file? I'm guessing I also wouldn't need the properties file in my case as I'm creating the connection via Java. How does liquibase know to run redshift sql commands (based on the tutorial you linked) ? As in, since my current error is that when I first try to create a table, it automatically runs the query to create the databasechangelog table via 

```CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))]```

And the `TAG` bit causes the error, doesn't work since it's Redshift reserved. Only if it's run manually with double quotation marks around TAG is my query able to succeed. Thanks for your help.

My Java code:

```
Connection conn = getConnection();
        if (conn != null) {
            try {
                Database database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(conn));
                Liquibase liquibase = new liquibase.Liquibase("path-to-xml.xml", new ClassLoaderResourceAccessor(), database);
                liquibase.setChangeLogParameter("account_name", account);
                liquibase.update(new Contexts(), new LabelExpression());
            } finally {
                conn.close();
            }
        }
```

current changelog file:

```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                   http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">

    <changeSet  id="1"  author="me">
        <createTable  tableName="${account_name}">
            <column  name="id"  type="int">
                <constraints  primaryKey="true"  nullable="false"/>
            </column>
        </createTable>
    </changeSet>

</databaseChangeLog>
```

**Comment by r2liquibase** [comment]
To run inline sql (sql that's in your changelog.xml): https://docs.liquibase.com/change-types/community/sql.html
To reference an external sql file: https://docs.liquibase.com/change-types/community/sql-file.html

Does that help?

**Comment by r2liquibase** [comment]
We have a Discord and a ton of other ways to contact the team. https://www.liquibase.org/contact

**Comment by akamathEG** [comment]
@r2liquibase Thanks, I've joined the discord you posted - we could carry on the convo there, if you'd like.
