### ISSUE TITLE
NOW() deprecated in Redshift

### ISSUE THREAD

**Issue by guybluebat** [liquibase/liquibase-redshift#9]
We started getting the following error from Liquibase when the databasechangelog table is updated:

Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.; [Failed SQL: INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1', 'xxxxxxxxxx', 'scripts/xxxxxxxxxxx.redshift.sql', NOW(), 318, 'xxxxxxxxxxxxxxxxxxx', 'sql', '', 'EXECUTED', 'all', NULL, '3.6.2', '1349680917')]

I tested this query on multiple redshift instances and they all failed. I submitted a support ticket to AWS and they replied to say that the NOW() function was recently fully deprecated from Redshift. Their suggestion was to use GETDATE or SYSDATE instead.

Because of the above error this module is now completely unusable. Is there any likelihood of this being fixed in the near future?

Thank you,
Guy

**Comment by guybluebat** [comment]
Ok, a few more notes to add here. I noticed that we were using liquibase v3.6.2 so I upgraded to 3.8.0 and re-tested - unfortunately the update still failed with the same error.

I then read through [this](https://forum.liquibase.org/topic/redshift-support) thread a bit more closely and saw the discussion there about NOW(). Following the discussion there, I tried adding "dbms:redshift" to our changelog (we use formatted sql, FYI), and when I ran liquibase update against my changelog, it worked. However, after checking the DB I realised that it just skipped the changeset completely as the changes in the changeset had not been made and the databasechangelog table hadn't been updated.

Our changelog files are all named "xxxxxxxxx.redshift.sql", so it seems like it should detect the dbms correctly (based on what I read in the thread linked above).

Is this a case of the dbms keyword not working with formatted sql?

**Comment by guybluebat** [comment]
Tried converting the problematic script to xml but it still shows the same behaviour. Adding dbms="redshift" causes liquibase to skip the changeset, leaving it out causes the databasechangelog table update to fail with the same original error related to NOW().

**Comment by sumanthneerumalla** [comment]
This issue should be closable. Seems to have been fixed in a March 2020 pull request from the community:

https://github.com/liquibase/liquibase-redshift/commit/216ac549d14f5f025dc4a518a8e10ed5bd78b2b6

**Comment by guybluebat** [comment]
Yes, after recently updating the library we noticed it seems to be working again. I forgot to come back here and post a comment, apologies.

**Comment by deepak3082** [comment]
Hi,
I have been trying to use this plugin for my Redshift database but haven't been able to get it to work. I am primarily facing two issues. 

1. Invalid operation: syntax error at or near "TAG". I got around this issue by creating the databasechangelog table manually.
2. Getting an error while inserting the record into the databasechangelog table, due to now() function being used by LB in the insert query.

I see that both the issues have been marked as fixed,however, i am still facing these issues. I cannot make any change manually in the jar files due to the nature of my project. Hence, would appreciate if somebody could provide any insights into this. Here is my `pom.xml`. I am also using dbms="redshift" in my changelog.xml file.

Thank you  in advance for any help.

```xml
<?xml` version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>local_redshift</groupId>
  <artifactId>local_redshift</artifactId>
  <version>0.0.1-SNAPSHOT</version>
<repositories>
    <repository>
      <id>redshift</id>
      <url>https://s3.amazonaws.com/redshift-maven-repository/release</url>
    </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-core</artifactId>
        <version>3.10.0</version>
    </dependency>
    <dependency>
	   <groupId>com.amazon.redshift</groupId>
	   <artifactId>redshift-jdbc42</artifactId>
	   <version>1.2.43.1067</version>
    </dependency>
    <dependency>
	    <groupId>org.liquibase.ext</groupId>
	    <artifactId>liquibase-redshift</artifactId>
	    <version>3.10.0</version>
    </dependency>
    <!--dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>1.8</version>
    </dependency>  -->
</dependencies>
 <build>
        <plugins>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                   <propertyFile>src/main/liquibase.redshift.properties</propertyFile>
                   <changeLogFile>src/main/changelog/changelog-1.0.0.0.1.xml</changeLogFile>
				  <promptOnNonLocalDatabase>false</promptOnNonLocalDatabase>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
